import React from 'react';
import { Platform, StyleSheet, useColorScheme, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { Feather } from '@expo/vector-icons';
import { BlurView } from 'expo-blur';
import { isLiquidGlassAvailable } from 'expo-glass-effect';
import { Tabs } from 'expo-router';
import { Icon, Label, NativeTabs } from 'expo-router/unstable-native-tabs';
import { SymbolView } from 'expo-symbols';
function NativeTabLayout() { return <NativeTabs><NativeTabs.Trigger name="index"><Icon sf={{ default:'house', selected:'house.fill' }} /><Label>Home</Label></NativeTabs.Trigger><NativeTabs.Trigger name="albums"><Icon sf={{ default:'square.stack', selected:'square.stack.fill' }} /><Label>Albums</Label></NativeTabs.Trigger><NativeTabs.Trigger name="favorites"><Icon sf={{ default:'heart', selected:'heart.fill' }} /><Label>Favorites</Label></NativeTabs.Trigger><NativeTabs.Trigger name="settings"><Icon sf={{ default:'slider.horizontal.3', selected:'slider.horizontal.3' }} /><Label>Settings</Label></NativeTabs.Trigger></NativeTabs>; }
function ClassicTabLayout() { const colors = useColors(); const colorScheme = useColorScheme(); const isDark = colorScheme === 'dark'; const isIOS = Platform.OS === 'ios'; const isWeb = Platform.OS === 'web'; return <Tabs screenOptions={{ headerShown:false, tabBarActiveTintColor:colors.primary, tabBarInactiveTintColor:colors.mutedForeground, tabBarStyle:{ position:'absolute', backgroundColor:isIOS?'transparent':colors.background, borderTopWidth:isWeb?1:0, borderTopColor:colors.border, elevation:0, ...(isWeb?{height:84}:{}) }, tabBarBackground:() => isIOS ? <BlurView intensity={100} tint={isDark?'dark':'light'} style={StyleSheet.absoluteFill} /> : isWeb ? <View style={[StyleSheet.absoluteFill,{backgroundColor:colors.background}]} /> : null }}><Tabs.Screen name="index" options={{ title:'Home', tabBarIcon:({color}) => isIOS ? <SymbolView name="house" tintColor={color} size={23} /> : <Feather name="home" size={21} color={color} /> }} /><Tabs.Screen name="albums" options={{ title:'Albums', tabBarIcon:({color}) => isIOS ? <SymbolView name="square.stack" tintColor={color} size={22} /> : <Feather name="layers" size={21} color={color} /> }} /><Tabs.Screen name="favorites" options={{ title:'Favorites', tabBarIcon:({color}) => isIOS ? <SymbolView name="heart" tintColor={color} size={22} /> : <Feather name="heart" size={21} color={color} /> }} /><Tabs.Screen name="settings" options={{ title:'Settings', tabBarIcon:({color}) => isIOS ? <SymbolView name="slider.horizontal.3" tintColor={color} size={22} /> : <Feather name="sliders" size={21} color={color} /> }} /></Tabs>; }
export default function TabLayout() { return isLiquidGlassAvailable() ? <NativeTabLayout /> : <ClassicTabLayout />; }
