import { useRouter } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { GalleryGrid } from '@/components/GalleryGrid';
import { ScreenHeader } from '@/components/ScreenHeader';
import { SearchBar } from '@/components/SearchBar';
import { GalleryContext } from '@/context/GalleryContext';
import { photos, Category } from '@/data/gallery';
import { useContext } from 'react';
const filters = ['All', 'Nature', 'Travel', 'People', 'Recent'] as const;
export default function HomeScreen() { const colors = useColors(); const router = useRouter(); const { favorites, toggleFavorite, deleted, gridColumns } = useContext(GalleryContext); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<(typeof filters)[number]>('All'); const items = useMemo(() => photos.filter((photo) => !deleted.includes(photo.id)).filter((photo) => filter === 'All' || photo.category === filter).filter((photo) => !query.trim() || [photo.title,photo.category,photo.album,photo.location].some((value) => value.toLowerCase().includes(query.toLowerCase()))), [deleted, filter, query]); return <View style={[styles.screen,{backgroundColor:colors.background}]}><ScreenHeader eyebrow="Your collection" title="Gallery" rightIcon="bell" /><View style={styles.search}><SearchBar value={query} onChangeText={setQuery} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <Text key={item} onPress={() => setFilter(item)} style={[styles.filter,{color:filter===item?colors.primary:colors.mutedForeground,backgroundColor:filter===item?colors.accent:'transparent',borderColor:filter===item?colors.primary:'transparent'}]}>{item}</Text>)}</ScrollView><View style={styles.sectionRow}><View><Text style={[styles.sectionTitle,{color:colors.foreground}]}>All moments</Text><Text style={[styles.sectionSub,{color:colors.mutedForeground}]}>{items.length} photographs · curated for you</Text></View><Text style={[styles.sort,{color:colors.primary}]}>Newest <Text style={{fontSize:14}}>⌄</Text></Text></View><GalleryGrid items={items} favorites={favorites} columns={gridColumns} onPhotoPress={(photo) => router.push({ pathname:'/viewer', params:{ id:photo.id } })} onFavorite={toggleFavorite} /></View>; }
const styles = StyleSheet.create({ screen:{flex:1}, search:{paddingHorizontal:20}, filters:{paddingHorizontal:20,paddingVertical:16,gap:8}, filter:{borderWidth:1,paddingHorizontal:16,paddingVertical:9,borderRadius:22,fontSize:13,fontWeight:'600',overflow:'hidden'}, sectionRow:{paddingHorizontal:20,paddingBottom:15,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'}, sectionTitle:{fontSize:22,fontWeight:'700',letterSpacing:-.4}, sectionSub:{fontSize:12,marginTop:5}, sort:{fontSize:12,fontWeight:'600',paddingBottom:3} });
