import React, { useContext } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { ScreenHeader } from '@/components/ScreenHeader';
import { GalleryContext } from '@/context/GalleryContext';
function Row({ icon, title, subtitle, children, onPress }: { icon:keyof typeof Feather.glyphMap; title:string; subtitle?:string; children?:React.ReactNode; onPress?:()=>void }) { const colors=useColors(); return <Pressable onPress={onPress} style={({pressed}) => [styles.row,{backgroundColor:colors.card,opacity:pressed?.75:1}]}><View style={[styles.rowIcon,{backgroundColor:colors.accent}]}><Feather name={icon} size={18} color={colors.primary}/></View><View style={styles.rowText}><Text style={[styles.rowTitle,{color:colors.foreground}]}>{title}</Text>{subtitle&&<Text style={[styles.rowSub,{color:colors.mutedForeground}]}>{subtitle}</Text>}</View>{children ?? <Feather name="chevron-right" size={18} color={colors.mutedForeground}/>}</Pressable>; }
export default function SettingsScreen() { const colors=useColors(); const { theme,setTheme,gridColumns,setGridColumns,slideshow,setSlideshow }=useContext(GalleryContext); return <View style={[styles.screen,{backgroundColor:colors.background}]}><ScreenHeader eyebrow="Make it yours" title="Settings"/><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Text style={[styles.label,{color:colors.mutedForeground}]}>APPEARANCE</Text><Row icon="sun" title="Appearance" subtitle={theme==='dark'?'Dark mode':'Light mode'}><Switch testID="theme-switch" value={theme==='dark'} onValueChange={(value)=>setTheme(value?'dark':'light')} trackColor={{false:colors.secondary,true:colors.primary}} thumbColor={theme==='dark'?colors.primaryForeground:'#FFFFFF'}/></Row><Text style={[styles.label,{color:colors.mutedForeground}]}>VIEWING</Text><Row icon="grid" title="Grid density" subtitle={gridColumns===2?'Comfortable':'Compact'}><View style={[styles.segment,{backgroundColor:colors.secondary}]}><Pressable onPress={()=>setGridColumns(2)} style={[styles.segmentButton,gridColumns===2&&{backgroundColor:colors.primary}]}><Text style={[styles.segmentText,{color:gridColumns===2?colors.primaryForeground:colors.mutedForeground}]}>2</Text></Pressable><Pressable onPress={()=>setGridColumns(3)} style={[styles.segmentButton,gridColumns===3&&{backgroundColor:colors.primary}]}><Text style={[styles.segmentText,{color:gridColumns===3?colors.primaryForeground:colors.mutedForeground}]}>3</Text></Pressable></View></Row><Row icon="play-circle" title="Slideshow" subtitle="Auto-play in immersive view"><Switch testID="slideshow-switch" value={slideshow} onValueChange={setSlideshow} trackColor={{false:colors.secondary,true:colors.primary}} thumbColor={slideshow?colors.primaryForeground:'#FFFFFF'}/></Row><Text style={[styles.label,{color:colors.mutedForeground}]}>LIBRARY</Text><Row icon="database" title="Storage" subtitle="18 photographs · 2.4 GB"/><Row icon="info" title="About Immersive Gallery" subtitle="Version 1.0.0"/><View style={[styles.footer,{borderTopColor:colors.border}]}><Text style={[styles.footerTitle,{color:colors.foreground}]}>Made for the moments</Text><Text style={[styles.footerSub,{color:colors.mutedForeground}]}>A quiet place for your visual life.</Text></View></ScrollView></View>; }
const styles=StyleSheet.create({screen:{flex:1},content:{paddingHorizontal:20,paddingBottom:110},label:{fontSize:11,letterSpacing:1.6,fontWeight:'700',marginTop:10,marginBottom:10},row:{minHeight:72,borderRadius:18,marginBottom:10,padding:12,flexDirection:'row',alignItems:'center'},rowIcon:{height:42,width:42,borderRadius:14,alignItems:'center',justifyContent:'center',marginRight:12},rowText:{flex:1},rowTitle:{fontSize:15,fontWeight:'600'},rowSub:{fontSize:12,marginTop:4},segment:{flexDirection:'row',borderRadius:10,padding:3,gap:2},segmentButton:{height:30,width:30,borderRadius:8,alignItems:'center',justifyContent:'center'},segmentText:{fontSize:13,fontWeight:'700'},footer:{marginTop:28,paddingTop:24,borderTopWidth:1,alignItems:'center'},footerTitle:{fontSize:16,fontWeight:'700'},footerSub:{fontSize:13,marginTop:6}});
